name: revival
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  easy_localization: ^3.0.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_intl: ^0.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  get_it: ^8.0.3
  go_router: ^15.1.1
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.20.2
  local_auth: ^2.3.0
  toastification: ^3.0.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_en_json_extractor: 0.0.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/image.png
    - assets/translations/
    - .env
