name: revival
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_intl: ^0.0.1
  go_router: ^15.1.1
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_en_json_extractor: 0.0.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
